### ISSUE TITLE
Flask code error

### ISSUE THREAD

**Issue by rilham97** [Ileriayo/python-whatsapp-bot#1]
I your code is working normally ? Because the Flask isn't running

**Comment by Ileriayo** [comment]
Hi @rilham97 my code is running as expected. I suspect that you may not have exported the FLASK_APP environment variable. I have updated the README.md file to include the commands for that. [Kindly check #5 in the Usage section of the Readme file.](https://github.com/Ileriayo/python-whatsapp-bot#usage)
