### ISSUE TITLE
does this still work???

### ISSUE THREAD

**Issue by 10sp** [Ileriayo/python-whatsapp-bot#2]
I want to use this project for my college project.

**Comment by Ileriayo** [comment]
Yep.

Lgtm 
<img width="899" alt="Screenshot 2022-06-03 at 16 51 08" src="https://user-images.githubusercontent.com/13166712/171901076-1b0706cb-4015-4289-a2e2-85c4b8d48dc4.png">

**Comment by exclushivity** [comment]
what's lgtm

**Comment by tomas7470** [comment]
Looks Good To Me..
